### PR TITLE
Support for the Soulreaper axe.

### PR DESCRIPTION
**Pull request by hugocowan**
Hey!

This PR is to add support for the Soulreaper axe's strength bonus.

There's a comment referencing [this PR](https://github.com/runelite/runelite/pull/17390) which is just there to show a potential improvement for the future.

Other than that this is feature complete and tested by myself to be working.

### CODE REVIEW

**Comment by j-cob44** [comment]
Hey @hugocowan! This looks great and I'm going to be testing it for the next few days if I can get my hands on an axe!

**Comment by hugocowan** [comment]
So I thought I would do some videos to show it working. 

Without using piety (prayer bonus), the numbers are accurate and I tested with a few different strength bonuses: 

https://github.com/j-cob44/max-hit-calc/assets/10326958/e89e8928-256c-468d-a18c-363f190dd8e3


When I enable piety though, the numbers are off:

https://github.com/j-cob44/max-hit-calc/assets/10326958/241d7315-87fd-4680-939c-b7f892f7b41d

And honestly it confuses me what's going on here. Especially since using the special attack at the end actually allows for a higher max hit than usual. According to the [wiki article](https://oldschool.runescape.wiki/w/Soulreaper_axe), I thought that the special max hit and standard max hit would be the same, but clearly I'm mistaken.

**Comment by j-cob44** [comment]
Hey @hugocowan! Thanks for the videos!

It definitely is very bizarre. What it looks like to me is a rounding error of some kind, which in my experience is usually the case when I start adding special bonuses in. The trick is finding the correct ordering of bonuses as they are calculated by the game.

My initial thought was that this line:
https://github.com/j-cob44/max-hit-calc/blob/3041c6dbc427bfc7bfc671087aa240e6e20481fb/src/main/java/com/maxhitcalc/MaxHit.java#L241

might need to be rewritten into two lines:
``` java
double effectiveStrength = Math.floor((Math.floor(strengthLevel * prayerBonus) + styleBonus + 8) * voidBonus);
effectiveStrength = Math.floor(effectiveStrength * soulStack);
```

and this shouldn't be a problem since soulStack is always returned as at least 1.

However, each time I watch the video you sent, I get less sure of my advice. Could you make two videos wearing the exact same equipment where the only difference is the use of piety?

Let me know what happens, and I'll keep investigating on my end too.

**Comment by j-cob44** [comment]
Hey @hugocowan! Thanks for the videos.

According to the wiki, the soul stack boost is additive with prayer bonus. So the fix could be by adding the soulStackBonus to prayerBonus instead of multiplying it into the equation. Prayer bonus is always returned as 1, so by making 

https://github.com/j-cob44/max-hit-calc/blob/3041c6dbc427bfc7bfc671087aa240e6e20481fb/src/main/java/com/maxhitcalc/MaxHit.java#L72-L78

return as just `0.06 * soulStack` is necessary.

Then before
https://github.com/j-cob44/max-hit-calc/blob/3041c6dbc427bfc7bfc671087aa240e6e20481fb/src/main/java/com/maxhitcalc/MaxHit.java#L241

we could write:
``` java
prayerBonus += soulStackBonus;

double effectiveStrength = Math.floor((Math.floor(strengthLevel * prayerBonus) + styleBonus + 8) * voidBonus); 
```

Let me know what happens since the wiki is wrong sometimes, and I'll keep investigating on my end too.

In the meantime, I'm still looking into why the max hit is different on the special attack. Could you make two new videos with the exact same equipment on and the only difference between the two is the use of piety?

**Comment by hugocowan** [comment]
Alright, so this is with the updated code, and with no armour on.

No piety:

https://github.com/j-cob44/max-hit-calc/assets/10326958/f4dca399-01c9-425a-a919-863f9bce9a01

Aand piety:

https://github.com/j-cob44/max-hit-calc/assets/10326958/31b2909e-2a57-4857-9606-82e9be1824f2


It looks like there is a bit of a rounding issue still with piety enabled, maybe it's a bit better though. Also the special attack definitely adds damage... so who knows how that should be calculated.

**Comment by hugocowan** [comment]
https://github.com/j-cob44/max-hit-calc/assets/10326958/74795a4c-bb0c-4ee7-9bfa-161dda402e55

Here's an example with piety and armour. Looks a lot better than before, but still some small rounding errors and a big difference with the spec hit.

**Comment by j-cob44** [comment]
I think there will definitely need to be a special attack calculation made. I reached out to Mod Ash on twitter for more info about the axe's special attack. In the past, he's been very helpful for clarification when I've asked him questions. So we'll see what he says.

In regard to the normal max hit, it definitely seems like a rounding error. Whenever I've encountered errors like these in the past, it's usually been a bit of trial and error at finding the correct order for when bonuses are applied. Unfortunately for us, I believe we are doing it correctly according to the wiki. With your videos, I'm able to work with the formulas on my end and see if I can match the result. Please let me know if you make any progress on it!

**Comment by j-cob44** [comment]
Hey @hugocowan, I talked with Mod Ash a little bit and still haven't quite narrowed down why the special attack is hitting higher than it is supposed to. In my testing and with my formula it seems to be 1 stack higher than it the normal attack for some reason. I'm not sure if that is the correct reason but it definitely seems to be an extra 6% higher of a hit.

For the normal hits, I'm almost to confident enough to integrate the code into the plugin. I have one request, just for more testing to see if I can narrow down where the rounding error is occurring. Could you make some videos going through each strength prayer spell up to piety, with no other items equipped? Thank you for you work and help so far.

**Comment by hugocowan** [comment]
https://github.com/j-cob44/max-hit-calc/assets/10326958/941d7305-bb1b-4535-913f-71a415cfba82

Here you go, all the strength bonuses in order. Sorry it took a while for me to get around to!

**Comment by j-cob44** [comment]
Hey @hugocowan, thanks for the video. Using it, I've found the value that the rounding is off by. The solution seems to be subtracting a constant value between [-0.009, -0.014] from the result of the stack formula. Currently I don't know why this is the case, but it reminds me of how the slayer helm is listed in game as a 15% damage bonus but is actually 16.66_% or 7/6. 

Changing here:
https://github.com/j-cob44/max-hit-calc/blob/83fe7c6ad9fa7cd79e81169ca89302c3e2127c31/src/main/java/com/maxhitcalc/MaxHit.java#L240-L244

to: 
```

if (prayerBonus > 1) 
{
    prayerBonus += soulStackBonus - 0.009; 
}
else
{
    prayerBonus += soulStackBonus;
}

```

Please try it out and let me know if this cleans up this rounding error. I'm still looking for the complete fix, but we can't let perfect be the enemy of good.

**Comment by hugocowan** [comment]
Wow okay, I would not have worked that out myself, nice one : D I'll give it a test.

**Comment by j-cob44** [comment]
Hopefully it works well, I've just been running it through the formula so hopefully it continues reproducing the same result when actually implemented. I'm confident the problem is when adding the soul stack bonus to the prayer bonus, I'll still be working on it in the meantime!

**Comment by hugocowan** [comment]
Yep, it works. Tried with/without armour + various strength prayers, always correct. Aside from the special attack obvs

**Comment by hugocowan** [comment]
Updated the PR

**Comment by j-cob44** [comment]
Awesome! Glad its working!

It seems the special attack is much easier to calculate as it is ```max hit * (0.06 * stack)``` and the bonus is calculated afterwards, like other special attacks. So it's bonus just needs to be added to the "list" in MaxSpec, at line 165, before the range checks:
```
if(weaponName.contains("Soulreaper axe"))
{
    return 1 + MaxHit.getSoulStackBonus(client);
}
```

However, the special attack max hit will then duplicate the stack bonus which makes it a little more complicated. I would propose adding a new argument to MaxHit.calculate() which is just a bool that checks if you are calculating for special attacks purposes. 

https://github.com/j-cob44/max-hit-calc/blob/ad1d9823324d6a94ef76c956ca33f23108c39123/src/main/java/com/maxhitcalc/MaxSpec.java#L309-L309

With that, you can pass a true value down through to MaxHit.calculateMeleeMaxHit() and add a check that doesn't add the soul stack bonuses when true.

https://github.com/j-cob44/max-hit-calc/blob/ad1d9823324d6a94ef76c956ca33f23108c39123/src/main/java/com/maxhitcalc/MaxHit.java#L240-L249

You could then encapsulate these lines above with something like ```if(!specialAttackCalc) { ... }```

But you can do it however you would like or if you find a more efficient way! Thanks for your work so far!

**Comment by hugocowan** [comment]
Alright, so that just works. I gave it a test briefly and yeah. Perfect scaling for max hit and max spec. Right every time. Let me know if you want more vids or anything like that.

**Comment by j-cob44** [comment]
Great! Can you make a video showing the special attack values working?

Also, when you're ready to do so, this can be changed back from a draft to a ready request!

**Comment by hugocowan** [comment]
https://github.com/j-cob44/max-hit-calc/assets/10326958/c9ab733d-9ba9-4232-a805-daca3ff62c6b

Here you go, a video with all strength bonuses showing spec hits. Also threw in some strength gear at the end.

**Review by j-cob44 — APPROVED** [review]
Fantastic! Thank you for your contribution!

**Pull request merged**
